name: ntds_2018
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.1.0
  - bleach=2.1.4
  - ca-certificates=2018.8.24
  - certifi=2018.8.24
  - cycler=0.10.0
  - decorator=4.3.0
  - entrypoints=0.2.3
  - freetype=2.9.1
  - git=2.19.0
  - html5lib=1.0.1
  - icu=58.2
  - ipykernel=4.8.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - jupyterlab=0.34.9
  - jupyterlab_launcher=0.13.1
  - kiwisolver=1.0.1
  - libpng=1.6.34
  - libsodium=1.0.16
  - markupsafe=1.0
  - matplotlib=3.0.0
  - mistune=0.8.3
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - networkx=2.2
  - notebook=5.6.0
  - numpy=1.15.1
  - openssl=1.0.2p
  - pandas=0.23.4
  - pandoc=2.3
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pickleshare=0.7.5
  - pip=18.0
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - pygments=2.2.0
  - pygsp=0.5.1
  - pyparsing=2.2.1
  - pyqt=5.6.0
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pyzmq=17.1.2
  - qt=5.6.2
  - qtconsole=4.4.1
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=40.4.0
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - sqlite=3.25.2
  - terminado=0.8.1
  - testpath=0.3.1
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - widgetsnbextension=3.4.2
  - zeromq=4.2.5
  - zlib=1.2.11
